[package]
name = "main-website"
version = "0.1.0"
authors = ["Clement Miao <clementmiao@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.0"
actix-files ="0.2.1"
tera = "1.2.0"
listenfd = "0.3"